# Generated by Django 3.2.24 on 2024-02-09 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='criminal_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('photo', models.FileField(upload_to='')),
                ('place', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='login_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='police_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('phone', models.BigIntegerField()),
                ('gender', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=25)),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suspecious_activity.login_table')),
            ],
        ),
        migrations.CreateModel(
            name='user_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=25)),
                ('place', models.CharField(max_length=100)),
                ('post', models.CharField(max_length=100)),
                ('pin', models.IntegerField()),
                ('phone', models.BigIntegerField()),
                ('email', models.CharField(max_length=25)),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suspecious_activity.login_table')),
            ],
        ),
        migrations.CreateModel(
            name='report_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('report', models.CharField(max_length=100)),
                ('policeid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suspecious_activity.police_table')),
            ],
        ),
        migrations.CreateModel(
            name='policestation_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('phone', models.BigIntegerField()),
                ('email', models.CharField(max_length=25)),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suspecious_activity.login_table')),
            ],
        ),
        migrations.AddField(
            model_name='police_table',
            name='policestation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suspecious_activity.policestation_table'),
        ),
        migrations.CreateModel(
            name='feedback_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('rating', models.FloatField()),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suspecious_activity.user_table')),
            ],
        ),
        migrations.CreateModel(
            name='complaint_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_details', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('reply', models.CharField(max_length=100)),
                ('report', models.CharField(max_length=100)),
                ('policestation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suspecious_activity.policestation_table')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suspecious_activity.user_table')),
            ],
        ),
        migrations.CreateModel(
            name='assigntask_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('status', models.CharField(max_length=100)),
                ('policeid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suspecious_activity.police_table')),
            ],
        ),
    ]
