# Generated by Django 3.2.24 on 2024-03-14 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suspecious_activity', '0002_assign_table_record_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint_table',
            name='report',
            field=models.FileField(upload_to=''),
        ),
    ]
