# Generated by Django 3.2.20 on 2024-03-29 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suspecious_activity', '0003_alter_complaint_table_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='criminal_table',
            name='policestation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='suspecious_activity.policestation_table'),
            preserve_default=False,
        ),
    ]
